// Shared cities list for influencer dashboard and cities page
export const cities = [
  { id: 16, name: "ALGER", image: "https://picsum.photos/seed/alger-1/400/500" },
  { id: 9, name: "BLIDA", image: "https://picsum.photos/seed/blida-1/400/500" },
  { id: 31, name: "ORAN", image: "https://picsum.photos/seed/oran-1/400/500" },
  { id: 15, name: "TIZI OUZOU", image: "https://picsum.photos/seed/tiziouzou-1/400/500" },
  { id: 6, name: "BÉJAÏA", image: "https://picsum.photos/seed/bejaia-1/400/500" },
  { id: 1, name: "ADRAR", image: "https://picsum.photos/seed/adrar-1/400/500" },
  { id: 2, name: "CHLEF", image: "https://picsum.photos/seed/chlef-1/400/500" },
  { id: 3, name: "LAGHOUAT", image: "https://picsum.photos/seed/laghouat-1/400/500" },
  { id: 4, name: "OUM EL BOUAGHI", image: "https://picsum.photos/seed/oumelbouaghi-1/400/500" },
  { id: 5, name: "BATNA", image: "https://picsum.photos/seed/batna-1/400/500" },
  { id: 7, name: "BISKRA", image: "https://picsum.photos/seed/biskra-1/400/500" },
  { id: 8, name: "BÉCHAR", image: "https://picsum.photos/seed/bechar-1/400/500" },
  { id: 10, name: "BOUIRA", image: "https://picsum.photos/seed/bouira-1/400/500" },
  { id: 11, name: "TAMANRASSET", image: "https://picsum.photos/seed/tamanrasset-1/400/500" },
  { id: 12, name: "TÉBESSA", image: "https://picsum.photos/seed/tebessa-1/400/500" },
  { id: 13, name: "TLEMCEN", image: "https://picsum.photos/seed/tlemcen-1/400/500" },
  { id: 14, name: "TIARET", image: "https://picsum.photos/seed/tiaret-1/400/500" },
  { id: 17, name: "DJELFA", image: "https://picsum.photos/seed/djelfa-1/400/500" },
  { id: 18, name: "JIJEL", image: "https://picsum.photos/seed/jijel-1/400/500" },
  { id: 19, name: "SÉTIF", image: "https://picsum.photos/seed/setif-1/400/500" },
  { id: 20, name: "SAÏDA", image: "https://picsum.photos/seed/saida-1/400/500" },
  { id: 21, name: "SKIKDA", image: "https://picsum.photos/seed/skikda-1/400/500" },
  { id: 22, name: "SIDI BEL ABBÈS", image: "https://picsum.photos/seed/sidibelabbes-1/400/500" },
  { id: 23, name: "ANNABA", image: "https://picsum.photos/seed/annaba-1/400/500" },
  { id: 24, name: "GUELMA", image: "https://picsum.photos/seed/guelma-1/400/500" },
  { id: 25, name: "CONSTANTINE", image: "https://picsum.photos/seed/constantine-1/400/500" },
  { id: 26, name: "MÉDÉA", image: "https://picsum.photos/seed/medea-1/400/500" },
  { id: 27, name: "MOSTAGANEM", image: "https://picsum.photos/seed/mostaganem-1/400/500" },
  { id: 28, name: "M'SILA", image: "https://picsum.photos/seed/msila-1/400/500" },
  { id: 29, name: "MASCARA", image: "https://picsum.photos/seed/mascara-1/400/500" },
  { id: 30, name: "OUARGLA", image: "https://picsum.photos/seed/ouargla-1/400/500" },
  { id: 32, name: "EL BAYADH", image: "https://picsum.photos/seed/elbayadh-1/400/500" },
  { id: 33, name: "ILLIZI", image: "https://picsum.photos/seed/illizi-1/400/500" },
  { id: 34, name: "BORDJ BOU ARRERIDJ", image: "https://picsum.photos/seed/bordjbouarreridj-1/400/500" },
  { id: 35, name: "BOUMERDÈS", image: "https://picsum.photos/seed/boumerdes-1/400/500" },
  { id: 36, name: "EL TARF", image: "https://picsum.photos/seed/eltarf-1/400/500" },
  { id: 37, name: "TINDOUF", image: "https://picsum.photos/seed/tindouf-1/400/500" },
  { id: 38, name: "TISSEMSILT", image: "https://picsum.photos/seed/tissemsilt-1/400/500" },
  { id: 39, name: "EL OUED", image: "https://picsum.photos/seed/eloued-1/400/500" },
  { id: 40, name: "KHENCHELA", image: "https://picsum.photos/seed/khenchela-1/400/500" },
  { id: 41, name: "SOUK AHRAS", image: "https://picsum.photos/seed/soukahras-1/400/500" },
  { id: 42, name: "TIPAZA", image: "https://picsum.photos/seed/tipaza-1/400/500" },
  { id: 43, name: "MILA", image: "https://picsum.photos/seed/mila-1/400/500" },
  { id: 44, name: "AÏN DEFLA", image: "https://picsum.photos/seed/aindefla-1/400/500" },
  { id: 45, name: "NAÂMA", image: "https://picsum.photos/seed/naama-1/400/500" },
  { id: 46, name: "AÏN TÉMOUCHENT", image: "https://picsum.photos/seed/aintemouchent-1/400/500" },
  { id: 47, name: "GHARDAÏA", image: "https://picsum.photos/seed/ghardaia-1/400/500" },
  { id: 48, name: "RELIZANE", image: "https://picsum.photos/seed/relizane-1/400/500" },
  { id: 49, name: "TIMIMOUN", image: "https://picsum.photos/seed/timimoun-1/400/500" },
  { id: 50, name: "BORDJ BADJI MOKHTAR", image: "https://picsum.photos/seed/bordjbadjimokhtar-1/400/500" },
  { id: 51, name: "OULED DJELLAL", image: "https://picsum.photos/seed/ouleddjellal-1/400/500" },
  { id: 52, name: "BÉNI ABBÈS", image: "https://picsum.photos/seed/beniabbes-1/400/500" },
  { id: 53, name: "IN SALAH", image: "https://picsum.photos/seed/insalah-1/400/500" },
  { id: 54, name: "IN GUEZZAM", image: "https://picsum.photos/seed/inguezzam-1/400/500" },
  { id: 55, name: "TOUGGOURT", image: "https://picsum.photos/seed/touggourt-1/400/500" },
  { id: 56, name: "DJANET", image: "https://picsum.photos/seed/djanet-1/400/500" },
  { id: 57, name: "EL M'GHAIR", image: "https://picsum.photos/seed/elmghair-1/400/500" },
  { id: 58, name: "EL MENIAA", image: "https://picsum.photos/seed/elmeniaa-1/400/500" },
];
